cache:
  paths:
    - node_modules/
    - .yarn
stages:
  - build
  - test
  - deploy
build:
  image: node:10
  stage: build
  script:
    - yarn config set cache-folder .yarn
    - yarn install --pure-lockfile --cache-folder .yarn
    - yarn build
  artifacts:
    paths:
      - ./build
  only:
    - master
test:
  image: node:10
  stage: test
  script:
    - echo "Running react test suite......"
    - yarn test
  only:
    - master
