name: NPM React CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - run: npm install -g npm@latest
    - run: rm -rf node_modules
    - run: npm install
    - run: npm update --save
    - run: npm run-script build
